esphome:
  name: leds
  platform: ESP32
  board: nodemcu-32s

<<: !include wifi.yaml

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
light:
  - platform: rgb
    name: "LEDs"
    blue: output_component1
    red: output_component2
    green: output_component3

# Example output entry
output:
  - platform: ledc
    id: output_component1
    pin: 25
  - platform: ledc
    id: output_component2
    pin: 26
  - platform: ledc
    id: output_component3
    pin: 27

<<: !include mqtt.yaml