esphome:
  name: sensors_temperature_basement
  platform: ESP32
  board: nodemcu-32s

<<: !include wifi.yaml

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
dallas:
  - pin: 22

# Individual sensors
sensor:
  - platform: dallas
    address: 0x9B0300A27968A928
    name: "Cold Room Temperature"
  - platform: dht
    pin: 23
    model: AM2302
    temperature:
      name: "Basement Temperature"
      filters:
        - median:
            window_size: 5
            send_every: 5
            send_first_at: 5
    humidity:
      name: "Basement Humidity"
      filters:
        - median:
            window_size: 5
            send_every: 5
            send_first_at: 5
    update_interval: 60s

<<: !include mqtt.yaml
