esphome:
  name: switch_standing_desk_studio
  platform: ESP32
  board: esp32cam

<<: !include wifi.yaml

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    pin: GPIO25
    id: standing
  - platform: template
    name: "Raise standing desk"
    icon: "mdi:human"
    turn_on_action:
    - switch.turn_on: standing
    - delay: 12000ms
    - switch.turn_off: standing
  - platform: gpio
    pin: GPIO26
    id: sitting
  - platform: template
    name: "Lower standing desk"
    icon: "mdi:table-chair"
    turn_on_action:
    - switch.turn_on: sitting
    - delay: 12000ms
    - switch.turn_off: sitting

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO14
    temperature:
      name: "Studio temperature"
      filters:
        - median:
            window_size: 5
            send_every: 5
            send_first_at: 5
    humidity:
      name: "Studio humidity"
      filters:
        - median:
            window_size: 5
            send_every: 5
            send_first_at: 5
    update_interval: 60s


<<: !include mqtt.yaml