esphome:
  name: test_leds
  platform: ESP8266
  board: nodemcuv2

<<: !include wifi.yaml

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
light:
  - platform: rgb
    name: "Living Room Lights"
    red: output_component1
    green: output_component2
    blue: output_component3

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D7
  - platform: esp8266_pwm
    id: output_component2
    pin: D6
  - platform: esp8266_pwm
    id: output_component3
    pin: D8

<<: !include mqtt.yaml